title: Haymarket theme
description: A GitHub Pages theme to easily launch Chicago DSA websites.
chapter:
  name: Chicago DSA
  location: Chicago
  url: https://www.chicagodsa.org/
google_analytics:
remote_theme: ChicagoDSA/Haymarket
plugins:
  - jekyll-seo-tag
  
